# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.13"

pre_release = false

preface = """\
The thirteenth patch release for containerd 1.5 includes a fix for
[GHSA-5ffw-gxpp-mxpf](https://github.com/containerd/containerd/security/advisories/GHSA-5ffw-gxpp-mxpf).

### Notable Updates

* **This is for testing the release of containerd.

See the changelog for complete list of changes"""
