# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.5.11"

pre_release = false

preface = """\
The twelve patch release for containerd 1.5.

### Notable Updates

* **This is for tkg patch releases/1.5

See the changelog for complete list of changes"""