# commit to be tagged for new release
commit = "HEAD"

project_name = "containerd"
github_repo = "containerd/containerd"
match_deps = "^github.com/(containerd/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.6"

pre_release = false

preface = """\
The sixth patch release for containerd 1.6 is for testing the release process

### Notable Updates

* **This is for only testing purpose

See the changelog for complete list of changes"""